{
 "title": "LanCache",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Cache Disk Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lancache_db",
     "rawSql": "SELECT KiBFree AS \"Free\", KiBUsed AS \"Used\" FROM lancache_db.cache_disk WHERE Location = 'data' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lancache_db",
     "rawSql": "SELECT SUM(Bytes), LStatus\r\nFROM lancache_db.access_logs\r\nWHERE $__timeFilter(LogDate)\r\nGROUP BY LStatus"
    }
   ]
  },
  {
   "title": "Downloaded From Upstream",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lancache_db",
     "rawSql": "SELECT SUM(Bytes), Upstream\r\nFROM lancache_db.access_logs\r\nWHERE $__timeFilter(LogDate) AND LStatus = 'MISS'\r\nGROUP BY Upstream"
    }
   ]
  },
  {
   "title": "Served From Upstream",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lancache_db",
     "rawSql": "SELECT SUM(Bytes), Upstream\r\nFROM lancache_db.access_logs\r\nWHERE $__timeFilter(LogDate) AND LStatus = 'HIT'\r\nGROUP BY Upstream"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 21, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "lancache_db",
     "rawSql": "SELECT *\r\nFROM(\r\n  SELECT\r\n    IP,\r\n    SUM(CASE WHEN LStatus = 'HIT' THEN Bytes ELSE 0 END) as HIT,\r\n    SUM(CASE WHEN LStatus = 'MISS' THEN Bytes ELSE 0 END) as MISS,\r\n    SUM(BYTES) as TOTAL\r\n  FROM lancache_db.access_logs\r\n  WHERE $__timeFilter(LogDate)\r\n  GROUP BY IP\r\n) as IPBytes\r\nORDER BY TOTAL"
    }
   ]
  },
  {
   "title": "Logs Size",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "lancache_db",
     "rawSql": "SELECT KiBUsed FROM lancache_db.cache_disk WHERE Location = 'logs' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Traffic History per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dataset": "lancache_db",
     "rawSql": "SELECT sum(Bytes) as Bytes, LStatus as status, STR_TO_DATE(minute_block, '%Y-%m-%d %H:%i') as ts\r\nFROM (\r\n\tSELECT Bytes, LStatus, DATE_FORMAT(LogDate, '%Y-%m-%d %H:%i') as minute_block FROM lancache_db.access_logs where Bytes > 0 and $__timeFilter(LogDate)\r\n) as blockbytes\r\ngroup by minute_block, LStatus;"
    }
   ]
  }
 ]
}